//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18052
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiasService.FiasUpdaterSRV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FiasUpdaterSRV.IFiasReal", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IFiasReal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFiasReal/Runable", ReplyAction="http://tempuri.org/IFiasReal/RunableResponse")]
        void Runable(string dir);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFiasRealChannel : FiasService.FiasUpdaterSRV.IFiasReal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FiasRealClient : System.ServiceModel.ClientBase<FiasService.FiasUpdaterSRV.IFiasReal>, FiasService.FiasUpdaterSRV.IFiasReal {
        
        public FiasRealClient() {
        }
        
        public FiasRealClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FiasRealClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiasRealClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FiasRealClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Runable(string dir) {
            base.Channel.Runable(dir);
        }
    }
}
